- name: Install supervisord
  apt: pkg=supervisor state=installed
  tags: thumbor_supervisord

- name: Enable thumbor conf for supervisor
  template: src="thumbor.conf" dest="/etc/supervisor/conf.d/thumbor.conf" owner=root group=root mode=0644
  tags: thumbor_supervisord

- name: Copy supervisor configuration
  template: src=supervisord.conf dest="/etc/supervisor/supervisord.conf" owner=root group=root mode=0644
  notify: restart supervisor
  tags: thumbor_supervisord
