- name: Copy site-available for nginx
  template: src="thumbor" dest="/etc/nginx/sites-available/thumbor"
  notify: restart nginx
  tags: nginx-vhost

- name: Create symbolic link to sites-enabled
  file: src=/etc/nginx/sites-available/thumbor dest=/etc/nginx/sites-enabled/thumbor owner=root group=root state=link
  notify: restart nginx
  tags: nginx-vhost

